/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyMain */

#ifndef _Included_MyMain
#define _Included_MyMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyMain
 * Method:    cfxn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyMain_cfxn
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
